version: 2.1
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run lint
      - run: npm test
